- name: Create Prometheus config directory
  file:
    path: /opt/prometheus
    state: directory

- name: Copy Prometheus config
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Run Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
